# Generated by Django 4.2 on 2023-04-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("website_url", models.TextField()),
                ("logo_url", models.TextField()),
                ("is_indie", models.BooleanField(default=False)),
            ],
        ),
    ]
