# Generated by Django 4.2 on 2023-04-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rpg_realms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("nationality", models.CharField(max_length=100)),
                ("photo_url", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="Publisher",
        ),
    ]
