# Generated by Django 4.2 on 2023-04-08 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rpg_realms", "0002_artist_delete_publisher"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Artist",
        ),
    ]
