# Generated by Django 4.2 on 2023-04-13 20:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rpg_realms", "0004_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="score",
            field=models.DecimalField(
                decimal_places=1,
                max_digits=2,
                validators=[
                    django.core.validators.MaxValueValidator(10),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
    ]
