# Generated by Django 4.2 on 2023-04-14 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rpg_realms", "0008_alter_review_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="date_posted",
            field=models.DateField(null=True),
        ),
    ]
